name: deployment

on:
  push:
    branches:
      - main
      - master

env:
  deploy_key: ${{ secrets.TEST_KEY }}

jobs:
  #  tests:
  #    if: startsWith(github.event.head_commit.message, 'deploy:')
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v1
  #      - uses: actions/setup-node@v1
  #        with:
  #          node-version: '20.x'
  #      - name: Test Build
  #        run: |
  #          yarn install
  #          yarn build
  deployment:
    # if: startsWith(github.event.head_commit.message, 'deploy:')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: docusaurus deploy
        env:
          USE_SSH: true
          GIT_USER: material-table-core-worker
        run: |
          yarn install
          yarn build
          cd build
          git config --global user.email "material.table.core@gmail.com"
          git config --global user.name "material-table-core-worker"
          echo "set git config"
          git init -b main
          echo "init git"
          echo "deploy_key: $GIT_USER"
          git remote add upstream https://$deploy_key@github.com/material-table-core/material-table-core.github.io
          echo "add upstream"
          git add .
          git commit -m "deploy: ${{ github.event.head_commit.message }}"
          echo "commit"
          git push upstream main --force
