name: deployment

on:
  push:
    branches:
      - main
      - master

jobs:
  #  tests:
  #    if: startsWith(github.event.head_commit.message, 'deploy:')
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v1
  #      - uses: actions/setup-node@v1
  #        with:
  #          node-version: '12.x'
  #      - name: Test Build
  #        run: |
  #          yarn install
  #          yarn build
  deployment:
    if: startsWith(github.event.head_commit.message, 'deploy:')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: docusaurus deploy
        env:
          USE_SSH: true
          GIT_USER: material-table-core-worker
        run: |
          git config --global user.email "material.table.core@gmail.com"
          git config --global user.name "material-table-core-worker"
          git remote add upstream https://github.com/material-table-core/material-table-core.github.io
          sudo apt install git-filter-repo
          yarn install
          yarn build
          git filter-repo --path build/
          git add .
          git commit -m "deploy: ${{ github.event.head_commit.message }}"
          git fetch upstream
          git push upstream upstream/main --force
